用 Doxygen 替代 API Docs
zhamao-robot/zhamao-framework pull request #192
Opened 2022-12-22 14:21 UTC by sunxyw

![圖片](https://user-images.githubusercontent.com/31698606/209156576-81101fb4-550d-4058-8957-8efe01f16590.png)

（现在凡是设计 GH Action 的更改就很怕炸
（谁能想到我原本是想生成生命周期图的呢

2022-12-22 16:32 UTC, crazywhalecc commented
目前链接涉及 VuePress 主题的一个问题，见：https://github.com/zpfz/vuepress-theme-antdocs/issues/49

2022-12-24 02:23 UTC, crazywhalecc requested changes
上游的主题已经修复此问题，依赖版本为 `>= 1.4.5`，同时使用 `target: '_blank'`

2022-12-24 06:40 UTC, crazywhalecc approved these changes

2022-12-24 06:41 UTC, merged

2022-12-25 14:09 UTC, zosfong commented
> 上游的主题已经修复此问题，依赖版本为 `>= 1.4.5`，同时使用 `target: '_blank'`

建议更新到 1.4.6 版本哈，1.4.5 版本在移动端适配有点bug。

2022-12-25 14:10 UTC, zpfz commented
> 上游的主题已经修复此问题，依赖版本为 `>= 1.4.5`，同时使用 `target: '_blank'`

建议更新到 1.4.6 版本哈，1.4.5 版本在移动端适配有点bug。