增加容器支持
zhamao-robot/zhamao-framework pull request #97
Opened 2022-04-04 12:53 UTC by sunxyw

2022-04-04 17:16 UTC, sunxyw commented
没找到一个合适的地方来初始化 WorkerContainer 和 Container，但目前来说基础功能已经能用了。

还有就是考虑有没有支持 Service Provider 的必要。

2022-04-07 14:53 UTC, sunxyw commented
基本搞定了，就差和框架结合，这个的话我不太清楚放在哪里比较合适。

先说下简单的用法：
`$abstract` 可以理解成别名，或者说 PSR-11 里边的 `id`，定义之后后续用这个来获取实例。
可以是：
- 类名/接口名：`FooInterface::class`，比较推荐用于需要依赖注入的
- 字符串：`foo`

`$concrete` 是具体实现，也就是获取的时候实际返回的。
可以是：
- 类名：`FooImpl::class`，获取的时候会自动实例化。
- 匿名函数：`callable`，获取的时候会执行并返回返回值。

`$callback` 可以是任意 `callable`，比如
- 类方法：`[Foo::class, 'bar']`
- 类静态方法：`\App\Foo::bar`
- 匿名函数（不确定）：`function () {}`

`$arguments` 的话，会传入到方法的参数里边。
如果方法参数的类型是某个类，会自动调用 `make` 方法进行实例化并注入。
如果是可选参数的话，会尝试注入默认值。
其他的话，需要手动指定值，比如
```php
public function baz(string $text);
```
就需要传入 `['text' => 'Hello, world']`，键名为参数名。


```php
// 普通绑定，每次获取实例都会重新 new 一个
container()->bind($abstract, $concrete);

// 单例绑定，同一个容器永远拿到同一个单例，只在第一次获取时实例化一次
container()->singleton($abstract, $concrete);

// 获取实例
container()->make($abstract, $arguments);
// 或者全局函数
resolve($abstract, $arguments);
// 等同于
app($abstract, $arguments);

// 调用方法
container()->call($callback, $arguments);
```

因为要适应 Swoole 这种常驻内存的场景，所以做了一些改造，主要就是分了进程容器和请求容器。
顾名思义，进程容器就是一个进程内一个，负责维持整个进程内的所有实例，请求容器就是每次请求一个，生命周期类似于 Context。
请求容器是继承进程容器的，可以用 `getParent` 拿到上级进程容器。
在请求容器上调用 `make` 的话，如果请求容器没有，会到进程容器找。

一般来说用户在使用的时候只需要接触到请求容器，因此 `container` 等全局函数都是返回的请求容器。

然后集成进框架的话，主要有两个地方，一个是 Worker 启动的时候，注册一些系统服务的绑定（比如 Robot 类等）：
```php
$worker_container = WorkerContainer::getInstance();
$worker_container->bind(XXX, YYY);
```

然后就是请求建立的时候，绑定一些用于请求的服务，比如 Context 之类：
```php
$request_container = new Container(); // 这里会自动获取进程容器
$request_container->bind(XXX, YYY);
```

接着调用方法的时候：
```php
$request_container->call([$class, $method], $args);
```
这样会自动实例化类（如果传入的是类名），然后执行方法。
比如：
```php
public function bar(Foo $foo) {
```
这种情况下，`Foo` 类会自动实例化并注入。

最后结束请求的时候*可能*需要手动清理一下：
```php
$request_container->flush();
```

请求容器的单例可能会有点毛病，这点没具体测试过。

2022-04-11 13:39 UTC, crazywhalecc commented on src/ZM/Event/SwooleEvent/OnWorkerStart.php
> +        new WorkerContainer();
这个搞不清楚用处。

2022-04-11 13:41 UTC, crazywhalecc commented on src/ZM/Framework.php
> +    private $swoole_config;
这里的 Swoole Set 如果要改名的话，`$swoole_config` 可能会有歧义，因为 Swoole 不只有 Server 的 config，而且还包含协程、异步、进程管理等配置，建议改成 `$swoole_server_config`。

2022-04-11 13:43 UTC, crazywhalecc commented on src/ZM/Framework.php
> +        $this->container = new Container();
建议 WorkerContainer 在 OnWorkerStart 事件开始初始化，此处为 Master 进程，本身也不符合 WorkerContainer 的定义。

2022-04-11 13:51 UTC, crazywhalecc requested changes

2022-04-11 13:51 UTC, crazywhalecc commented on src/ZM/Framework.php
> +        DataProvider::createIfNotExists(app('path.data'));
此处同理，先从 Config 获取，因为 Config 本身也是全局可以获取的模块。

2022-04-11 13:51 UTC, crazywhalecc commented on src/ZM/Framework.php
> +    protected function bindPathsInContainer(): void
+1

2022-04-15 12:40 UTC, crazywhalecc approved these changes
没问题，可以合并了。

另外，可以给 onRequest 和 onOpen 等事件后期也逐渐套上 DI，目前我看是只给 message 套了。

2022-04-15 12:40 UTC, crazywhalecc approved these changes
没问题，可以合并了。

另外，可以给 onRequest 和 onOpen 等事件后期也逐渐套上 DI，目前我看是只给 message 套了。

2022-04-15 15:07 UTC, merged